window.fj=window.fj||{};window.fj.event={};window.fj.event=(function(){let _eventFuncData={};function removeFromArray(array,item){if(!Array.isArray(array)){console.error(new TypeError("ERR_ARGUMENTS"));return;}
let index=array.indexOf(item);if(index!==-1){array.splice(index,1);}}
function deleteCache(cache){for(let key in _eventFuncData){if(_eventFuncData.hasOwnProperty(key)){removeFromArray(_eventFuncData[key],cache);}}}
return{subscribe:function(eventType,callback,once){let cache={callback,once};_eventFuncData[eventType]=_eventFuncData[eventType]||[];_eventFuncData[eventType].push(cache);return()=>{deleteCache(cache);};},dispatch:function(eventType,data){if(_eventFuncData[eventType]){let shouldDeleteOnceCache=[];_eventFuncData[eventType].forEach((cache)=>{cache.callback(data);if(cache.once){shouldDeleteOnceCache.push(cache);}});shouldDeleteOnceCache.forEach((cache)=>{deleteCache(cache);});}},};})();window.fj.network={fetch:function(url,data,successCallback,errorCallback){let f=fetch(url,data).then((response)=>{try{this._checkLogin(response);}catch(e){console.log(e);}
if(json.code===200){successCallback(response);}else{errorCallback(response);}}).then((stream)=>{}).then((blob)=>{}).catch((error)=>{});return f;},get:function(url,data,header,successCallback,errorCallback){let g=$.ajax({url:url,type:"GET",header:header,data:data,success:function(json){try{this._checkLogin(json);}catch(e){console.log(e);}
if(json.code===200){successCallback(json);}else{errorCallback(json);}},error:function(json){errorCallback(json);},});return g;},post:function(url,data,header,successCallback,errorCallback){let p=$.ajax({url:url,type:"POST",header:header,data:data,success:function(json){try{this._checkLogin(json);}catch(e){console.log(e);}
if(json.code===200){successCallback(json);}else{errorCallback(json);}},error:function(json){errorCallback(json);},});return p;},_checkLogin:function(json){if(json.code===214){window.PanelFunc.showSignUpPane();}},};window.FJTools={post:function(url,postData={},successCallback=null,errorCallback=null,showMessage=true,){if(window.csrf_token){postData[csrf_token]=1;}
$.ajax({url:url,type:"POST",data:postData,success:function(json){if(335==json.code){window.fj.event.dispatch("KEEP_ALIVE_INVALID",json);if(window.fjpopup){let message="";let title="";let Refresh="";let Close="";switch(window.language_tag){case "es":message="La información de tu cuenta es inválida ahora, por favor recarga la página.";title="La Sesión Caduco";Refresh="Refrescar";Close="Cerrar";break;case "pt":message="As informações da sua conta são inválidas agora, atualize a página.";title="Login Expirado";Refresh="Refrescar";Close="Perto";break;case "de":message="Ihre Kontodaten sind jetzt ungültig, bitte aktualisieren Sie die Seite.";title="Login Abgelaufen";Refresh="Auffrischen";Close="Schließen";break;case "fr":message="Vos identifiants sont erronés, veuillez actualiser la page.";title="Connexion expirée";Refresh="Rafraîchir";Close="Fermer";break;case "jp":message="お使いのアカウントは無効になっています。ページを更新してください。";title="ログイン期限が切れました";Refresh="リフレッシュ";Close="閉じる";break;case "tw":message="帳號資訊不存在，請刷新頁面後重試。";title="登錄失效";Refresh="刷新";Close="關閉";break;case "cn":message="您的账号信息无效，请刷新页面后重试。";title="登录失效";Refresh="刷新";Close="关闭";break;default:message="Your account info is invalid now, please refresh the page.";title="Login Expired";Refresh="Refresh";Close="Close";}
window.fjpopup.openType1(title,message,Refresh,function(){window.location.href="/?action=signin";},Close,);}}else{if(json.csrf_token){window.csrf_token=json.token;}}
if(successCallback){successCallback(json);}},error:function(){if(window.fjmessage&&showMessage){let tag="en";let matches=document.location.pathname.match(/\/([a-z]{2})\//);if(matches&&matches[1]){tag=matches[1];}
let message={en:"Failed to connect network.",cn:"连接网络失败。",tw:"連接網路失敗。",jp:"ネットワークに接続できませんでした。",de:"Verbindung zum Netzwerk fehlgeschlagen.",es:"Error de conexión de red.",pt:"Falha a ligar à rede!",fr:"Échec de la connexion au réseau !",}[tag];fjmessage.addMessage(message,"warning");}
if(errorCallback){errorCallback();}},});},isMobile:function(){let Sys={};let ua=navigator.userAgent.toLowerCase();let s;(s=ua.match(/rv:([\d.]+)\) like gecko/))?(Sys.ie=s[1]):(s=ua.match(/msie ([\d.]+)/))?(Sys.ie=s[1]):(s=ua.match(/edge\/([\d.]+)/))?(Sys.edge=s[1]):(s=ua.match(/firefox\/([\d.]+)/))?(Sys.firefox=s[1]):(s=ua.match(/chrome\/([\d.]+)/))?(Sys.chrome=s[1]):(s=ua.match(/opera.([\d.]+)/))?(Sys.opera=s[1]):(s=ua.match(/version\/([\d.]+).*safari/))?(Sys.safari=s[1]):0;if(ua.match(/mobile/)){return true;}
return false;},loadCSS:function(url,id,elementId){let d=document,s="link";if(d.getElementById(id)){return;}
let link=d.createElement(s),flink=d.getElementById(elementId);if(!flink)flink=d.getElementsByTagName(s)[0];link.type="text/css";link.rel="stylesheet";link.href=url;link.id=id;flink.parentNode.insertBefore(link,flink);},loadJS:function(url,id,elementId){let d=document,s="script";if(d.getElementById(id)){return;}
let js,fjs=d.getElementById(elementId);if(!fjs)fjs=d.getElementsByTagName(s)[0];js=d.createElement(s);js.id=id;js.src=url;js.type="text/javascript";fjs.parentNode.insertBefore(js,fjs);},loadThirdPartyJs:function(url){if(localStorage.getItem("cookie_privacy_shown")==="1"){let d=document,s="script";let js,fjs=d.getElementsByTagName(s)[0];js=d.createElement(s);js.src=url;js.type="text/javascript";js.async=true;js.defer=true;fjs.parentNode.insertBefore(js,fjs);}},};window.fj.setInstallButton=(ele)=>{if(ele){window.fj.installBtn=ele;window.fj.updateInstallButtonVisible();}};window.fj.updateInstallButtonVisible=()=>{if(!window.fj.installBtn)return;if(window.fj.deferredPrompt){const SHOW_HEIGHT=650;if($(window).height()>SHOW_HEIGHT){$(window.fj.installBtn).show();}else{$(window.fj.installBtn).hide();}}else{$(window.fj.installBtn).hide();}};window.fj.installChromeApp=(e)=>{const promptEvent=window.fj.deferredPrompt;if(!promptEvent){return;}
promptEvent.prompt();promptEvent.userChoice.then((result)=>{window.fj.deferredPrompt=null;if(result&&window.ealog){let location="home";if(e=="footer"){let href=window.location.href;let index=href.lastIndexOf("/");let str=href.substring(index+1,href.length);location="footer_"+str;}
window.ealog.addEvent("click chrome app download",{location:location,});}});};window.addEventListener("beforeinstallprompt",(event)=>{window.fj.deferredPrompt=event;window.fj.updateInstallButtonVisible();});window.addEventListener("appinstalled",(evt)=>{window.fj.deferredPrompt=null;if(window.fj.installBtn)$(window.fj.installBtn).hide();});document.addEventListener("DOMContentLoaded",function(){const timeout=120000;let keepaliveTime=new Date().getTime();window.setInterval(function(){if(!window.fjuser||!window.fjuser.info||!window.fjuser.info.result){return;}
if(new Date().getTime()-keepaliveTime<=timeout){return;}
FJTools.post("/keepalive",()=>{},()=>{},false,);},timeout);window.fj.event.subscribe("POSTPONE_KEEPALIVE_EVENT",()=>{keepaliveTime=new Date().getTime();});let displayMode="browser";if(navigator.standalone){displayMode="standalone-ios";}
if(window.matchMedia("(display-mode: standalone)").matches){displayMode="standalone";}
window.fj.displayMode=displayMode;window.matchMedia("(display-mode: standalone)").addListener((evt)=>{let displayMode="browser";if(evt.matches){displayMode="standalone";}
if(window.fj.displayMode!=displayMode){window.fj.displayMode=displayMode;if(displayMode=="standalone"&&window.location.href.indexOf("/editor/")==-1){window.location.href="/editor/?source=pwa";}else if(window.fj.installBtn){$(window.fj.installBtn).hide();}}});});let domain=window.location.hostname;document.cookie="_fcad="+domain+"; path=/";if(!domain.includes("flexclip")&&!domain.includes("smartvideomaker")){window.location.href="https://www.flexclip.com";}